apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ms2-selfsigned-ca
  namespace: default
spec:
  isCA: true
  commonName: ms2-root-ca
  secretName: ms2-root-ca-secret
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ms2-ca-issuer
  namespace: default
spec:
  ca:
    secretName: ms2-root-ca-secret
